language: python
python:
    - "3.6"
services:
    - docker
before_install:
    - docker build -t draft-kings-fun .
script:
    - docker run draft-kings-fun flake8 draftfast
    - docker run draft-kings-fun nosetests --with-coverage --cover-package=.
